extends Node2D

onready var counter : float = Autoload.get_rand_time()

#
#
#
#func _process(delta) -> void:
#	counter -= delta
#
#
#
#	if counter <= 0:
		counter = Autoload.get_rand_time()
#
#
#		var q_VisualServer : VisualServer = VisualServer.new()
#
#		VisualServer.black_bars_set_images(
#		VisualServer.black_bars_set_margins(
#		VisualServer.camera_create()
#		VisualServer.camera_set_cull_mask(
#		VisualServer.camera_set_environment(
#		VisualServer.camera_set_frustum(
#		VisualServer.camera_set_orthogonal(
#		VisualServer.camera_set_perspective(
#		VisualServer.camera_set_transform(
#		VisualServer.camera_set_use_vertical_aspect(
#
#		VisualServer.canvas_create()
#		VisualServer.canvas_item_add_circle(
#		VisualServer.canvas_item_add_clip_ignore(
#		VisualServer.canvas_item_add_line(
#		VisualServer.canvas_item_add_mesh(
#		VisualServer.canvas_item_add_multimesh(
#		VisualServer.canvas_item_add_nine_patch(
#		VisualServer.canvas_item_add_particles(
#		VisualServer.canvas_item_add_polygon(
#		VisualServer.canvas_item_add_polyline(
#		VisualServer.canvas_item_add_primitive(
#		VisualServer.canvas_item_add_rect(
#		VisualServer.canvas_item_add_set_transform(
#		VisualServer.canvas_item_add_texture_rect(
#		VisualServer.canvas_item_add_texture_rect_region(
#		VisualServer.canvas_item_add_triangle_array(
#		VisualServer.canvas_item_clear(
#		VisualServer.canvas_item_create()
#		VisualServer.canvas_item_set_clip(
#		VisualServer.canvas_item_set_copy_to_backbuffer(
#		VisualServer.canvas_item_set_custom_rect(
#		VisualServer.canvas_item_set_distance_field_mode(
#		VisualServer.canvas_item_set_draw_behind_parent(
#		VisualServer.canvas_item_set_draw_index(
#		VisualServer.canvas_item_set_light_mask(
#		VisualServer.canvas_item_set_material(
#		VisualServer.canvas_item_set_modulate(
#		VisualServer.canvas_item_set_parent(
#		VisualServer.canvas_item_set_self_modulate(
#		VisualServer.canvas_item_set_sort_children_by_y(
#		VisualServer.canvas_item_set_transform(
#		VisualServer.canvas_item_set_use_parent_material(
#		VisualServer.canvas_item_set_visible(
#		VisualServer.canvas_item_set_z_as_relative_to_parent(
#		VisualServer.canvas_item_set_z_index(
#		VisualServer.canvas_light_attach_to_canvas(
#		VisualServer.canvas_light_create()
#		VisualServer.canvas_light_occluder_attach_to_canvas(
#		VisualServer.canvas_light_occluder_create()
#		VisualServer.canvas_light_occluder_set_enabled(
#		VisualServer.canvas_light_occluder_set_light_mask(
#		VisualServer.canvas_light_occluder_set_polygon(
#		VisualServer.canvas_light_occluder_set_transform(
#		VisualServer.canvas_light_set_color(
#		VisualServer.canvas_light_set_enabled(
#		VisualServer.canvas_light_set_energy(
#		VisualServer.canvas_light_set_height(
#		VisualServer.canvas_light_set_item_cull_mask(
#		VisualServer.canvas_light_set_item_shadow_cull_mask(
#		VisualServer.canvas_light_set_layer_range(
#		VisualServer.canvas_light_set_mode(
#		VisualServer.canvas_light_set_scale(
#		VisualServer.canvas_light_set_shadow_buffer_size(
#		VisualServer.canvas_light_set_shadow_color(
#		VisualServer.canvas_light_set_shadow_enabled(
#		VisualServer.canvas_light_set_shadow_filter(
#		VisualServer.canvas_light_set_shadow_gradient_length(
#		VisualServer.canvas_light_set_shadow_smooth(
#		VisualServer.canvas_light_set_texture(
#		VisualServer.canvas_light_set_texture_offset(
#		VisualServer.canvas_light_set_transform(
#		VisualServer.canvas_light_set_z_range(
#		VisualServer.canvas_occluder_polygon_create()
#		VisualServer.canvas_occluder_polygon_set_cull_mode(
#		VisualServer.canvas_occluder_polygon_set_shape(
#		VisualServer.canvas_occluder_polygon_set_shape_as_lines(
#		VisualServer.canvas_set_item_mirroring(
#		VisualServer.canvas_set_modulate(
#		VisualServer.directional_light_create()
#		VisualServer.draw(
#		VisualServer.environment_create()
#		VisualServer.environment_set_adjustment(
#		VisualServer.environment_set_ambient_light(
#		VisualServer.environment_set_background(
#		VisualServer.environment_set_bg_color(
#		VisualServer.environment_set_bg_energy(
#		VisualServer.environment_set_canvas_max_layer(
#		VisualServer.environment_set_dof_blur_far(
#		VisualServer.environment_set_dof_blur_near(
#		VisualServer.environment_set_fog(
#		VisualServer.environment_set_fog_depth(
#		VisualServer.environment_set_glow(
#		VisualServer.environment_set_sky(
#		VisualServer.environment_set_sky_custom_fov(
#		VisualServer.environment_set_sky_orientation(
#		VisualServer.environment_set_ssao(
#		VisualServer.environment_set_ssr(
#		VisualServer.environment_set_tonemap(
#		VisualServer.finish()
#		VisualServer.force_draw(
#		VisualServer.force_sync()
#		VisualServer.get_render_info(
#		VisualServer.get_test_cube()
#		VisualServer.get_test_texture()
#		VisualServer.get_white_texture()
#		VisualServer.gi_probe_create()
#		VisualServer.gi_probe_get_bias(
#		VisualServer.gi_probe_get_bounds(
#		VisualServer.gi_probe_get_cell_size(
#		VisualServer.gi_probe_get_dynamic_data(
#		VisualServer.gi_probe_get_dynamic_range(
#		VisualServer.gi_probe_get_energy(
#		VisualServer.gi_probe_get_normal_bias(
#		VisualServer.gi_probe_get_propagation(
#		VisualServer.gi_probe_get_to_cell_xform(
#		VisualServer.gi_probe_is_compressed(
#		VisualServer.gi_probe_is_interior(
#		VisualServer.gi_probe_set_bias(
#		VisualServer.gi_probe_set_bounds(
#		VisualServer.gi_probe_set_cell_size(
#		VisualServer.gi_probe_set_compress(
#		VisualServer.gi_probe_set_dynamic_data(
#		VisualServer.gi_probe_set_dynamic_range(
#		VisualServer.gi_probe_set_energy(
#		VisualServer.gi_probe_set_interior(
#		VisualServer.gi_probe_set_normal_bias(
#		VisualServer.gi_probe_set_propagation(
#		VisualServer.gi_probe_set_to_cell_xform(
#		VisualServer.has_changed()
#		VisualServer.has_feature(
#		VisualServer.has_os_feature(
#		VisualServer.immediate_begin(
#		VisualServer.immediate_clear(
#		VisualServer.immediate_color(
#		VisualServer.immediate_end(
#		VisualServer.immediate_get_material(
#		VisualServer.immediate_normal(
#		VisualServer.immediate_set_material(
#		VisualServer.immediate_tangent(
#		VisualServer.immediate_uv(
#		VisualServer.immediate_uv2(
#		VisualServer.immediate_vertex(
#		VisualServer.immediate_vertex_2d(
#		VisualServer.init()
#		VisualServer.instance_attach_object_instance_id(
#		VisualServer.instance_attach_skeleton(
#		VisualServer.instance_create()
#		VisualServer.instance_create2(
#		VisualServer.instance_geometry_set_as_instance_lod(
#		VisualServer.instance_geometry_set_cast_shadows_setting(
#		VisualServer.instance_geometry_set_draw_range(
#		VisualServer.instance_geometry_set_flag(
#		VisualServer.instance_geometry_set_material_override(
#		VisualServer.instance_set_base(
#		VisualServer.instance_set_blend_shape_weight(
#		VisualServer.instance_set_custom_aabb(
#		VisualServer.instance_set_exterior(
#		VisualServer.instance_set_extra_visibility_margin(
#		VisualServer.instance_set_layer_mask(
#		VisualServer.instance_set_scenario(
#		VisualServer.instance_set_surface_material(
#		VisualServer.instance_set_transform(
#		VisualServer.instance_set_use_lightmap(
#		VisualServer.instance_set_visible(
#		VisualServer.instances_cull_aabb(
#		VisualServer.instances_cull_convex(
#		VisualServer.instances_cull_ray(
#		VisualServer.light_directional_set_blend_splits(
#		VisualServer.light_directional_set_shadow_depth_range_mode(
#		VisualServer.light_directional_set_shadow_mode(
#		VisualServer.light_omni_set_shadow_detail(
#		VisualServer.light_omni_set_shadow_mode(
#		VisualServer.light_set_color(
#		VisualServer.light_set_cull_mask(
#		VisualServer.light_set_negative(
#		VisualServer.light_set_param(
#		VisualServer.light_set_projector(
#		VisualServer.light_set_reverse_cull_face_mode(
#		VisualServer.light_set_shadow(
#		VisualServer.light_set_shadow_color(
#		VisualServer.light_set_use_gi(
#		VisualServer.lightmap_capture_create()
#		VisualServer.lightmap_capture_get_bounds(
#		VisualServer.lightmap_capture_get_energy(
#		VisualServer.lightmap_capture_get_octree(
#		VisualServer.lightmap_capture_get_octree_cell_subdiv(
#		VisualServer.lightmap_capture_get_octree_cell_transform(
#		VisualServer.lightmap_capture_set_bounds(
#		VisualServer.lightmap_capture_set_energy(
#		VisualServer.lightmap_capture_set_octree(
#		VisualServer.lightmap_capture_set_octree_cell_subdiv(
#		VisualServer.lightmap_capture_set_octree_cell_transform(
#		VisualServer.make_sphere_mesh(
#		VisualServer.material_create()
#		VisualServer.material_get_param(
#		VisualServer.material_get_param_default(
#		VisualServer.material_get_shader(
#		VisualServer.material_set_line_width(
#		VisualServer.material_set_next_pass(
#		VisualServer.material_set_param(
#		VisualServer.material_set_render_priority(
#		VisualServer.material_set_shader(
#		VisualServer.mesh_add_surface_from_arrays(
#		VisualServer.mesh_clear(
#		VisualServer.mesh_create()
#		VisualServer.mesh_get_blend_shape_count(
#		VisualServer.mesh_get_blend_shape_mode(
#		VisualServer.mesh_get_custom_aabb(
#		VisualServer.mesh_get_surface_count(
#		VisualServer.mesh_remove_surface(
#		VisualServer.mesh_set_blend_shape_count(
#		VisualServer.mesh_set_blend_shape_mode(
#		VisualServer.mesh_set_custom_aabb(
#		VisualServer.mesh_surface_get_aabb(
#		VisualServer.mesh_surface_get_array(
#		VisualServer.mesh_surface_get_array_index_len(
#		VisualServer.mesh_surface_get_array_len(
#		VisualServer.mesh_surface_get_arrays(
#		VisualServer.mesh_surface_get_blend_shape_arrays(
#		VisualServer.mesh_surface_get_format(
#		VisualServer.mesh_surface_get_format_offset(
#		VisualServer.mesh_surface_get_format_stride(
#		VisualServer.mesh_surface_get_index_array(
#		VisualServer.mesh_surface_get_material(
#		VisualServer.mesh_surface_get_primitive_type(
#		VisualServer.mesh_surface_get_skeleton_aabb(
#		VisualServer.mesh_surface_set_material(
#		VisualServer.multimesh_allocate(
#		VisualServer.multimesh_get_aabb(
#		VisualServer.multimesh_get_instance_count(
#		VisualServer.multimesh_get_mesh(
#		VisualServer.multimesh_get_visible_instances(
#		VisualServer.multimesh_instance_get_color(
#		VisualServer.multimesh_instance_get_custom_data(
#		VisualServer.multimesh_instance_get_transform(
#		VisualServer.multimesh_instance_get_transform_2d(
#		VisualServer.multimesh_instance_set_color(
#		VisualServer.multimesh_instance_set_custom_data(
#		VisualServer.multimesh_instance_set_transform(
#		VisualServer.multimesh_instance_set_transform_2d(
#		VisualServer.multimesh_set_as_bulk_array(
#		VisualServer.multimesh_set_mesh(
#
#		VisualServer.omni_light_create()
#
#		VisualServer.particles_create()
#		VisualServer.particles_get_current_aabb(
#		VisualServer.particles_get_emitting(
#		VisualServer.particles_restart(
#		VisualServer.particles_set_amount(
#		VisualServer.particles_set_custom_aabb(
#		VisualServer.particles_set_draw_order(
#		VisualServer.particles_set_draw_pass_mesh(
#		VisualServer.particles_set_draw_passes(
#		VisualServer.particles_set_emission_transform(
#		VisualServer.particles_set_emitting(
#		VisualServer.particles_set_explosiveness_ratio(
#		VisualServer.particles_set_fixed_fps(
#		VisualServer.particles_set_fractional_delta(
#		VisualServer.particles_set_lifetime(
#		VisualServer.particles_set_one_shot(
#		VisualServer.particles_set_pre_process_time(
#		VisualServer.particles_set_process_material(
#		VisualServer.particles_set_randomness_ratio(
#		VisualServer.particles_set_speed_scale(
#		VisualServer.particles_set_use_local_coordinates(
#		VisualServer.reflection_probe_create()
#		VisualServer.reflection_probe_set_as_interior(
#		VisualServer.reflection_probe_set_cull_mask(
#		VisualServer.reflection_probe_set_enable_box_projection(
#		VisualServer.reflection_probe_set_enable_shadows(
#		VisualServer.reflection_probe_set_extents(
#		VisualServer.reflection_probe_set_intensity(
#		VisualServer.reflection_probe_set_interior_ambient(
#		VisualServer.reflection_probe_set_interior_ambient_energy(
#		VisualServer.reflection_probe_set_interior_ambient_probe_contribution(
#		VisualServer.reflection_probe_set_max_distance(
#		VisualServer.reflection_probe_set_origin_offset(
#		VisualServer.reflection_probe_set_update_mode(
#		VisualServer.request_frame_drawn_callback(
#		VisualServer.scenario_create()
#		VisualServer.scenario_set_debug(
#		VisualServer.scenario_set_environment(
#		VisualServer.scenario_set_fallback_environment(
#		VisualServer.scenario_set_reflection_atlas_size(
#		VisualServer.set_boot_image(
#		VisualServer.set_debug_generate_wireframes(
#		VisualServer.set_default_clear_color(
#		VisualServer.shader_create()
#		VisualServer.shader_get_code(
#		VisualServer.shader_get_default_texture_param(
#		VisualServer.shader_get_param_list(
#		VisualServer.shader_set_code(
#		VisualServer.shader_set_default_texture_param(
#		VisualServer.skeleton_allocate(
#		VisualServer.skeleton_bone_get_transform(
#		VisualServer.skeleton_bone_get_transform_2d(
#		VisualServer.skeleton_bone_set_transform(
#		VisualServer.skeleton_bone_set_transform_2d(
#		VisualServer.skeleton_create()
#		VisualServer.skeleton_get_bone_count(
#		VisualServer.sky_create()
#		VisualServer.spot_light_create()
#		VisualServer.sync()
#		VisualServer.texture_allocate(
#		VisualServer.texture_create()
#		VisualServer.texture_create_from_image(
#		VisualServer.texture_debug_usage()
#		VisualServer.texture_get_data(
#		VisualServer.texture_get_depth(
#		VisualServer.texture_get_flags(
#		VisualServer.texture_get_format(
#		VisualServer.texture_get_height(
#		VisualServer.texture_get_path(
#		VisualServer.texture_get_texid(
#		VisualServer.texture_get_type(
#		VisualServer.texture_get_width(
#		VisualServer.texture_set_data(
#		VisualServer.texture_set_flags(
#		VisualServer.texture_set_path(
#		VisualServer.texture_set_shrink_all_x2_on_set_data(
#		VisualServer.texture_set_size_override(
#		VisualServer.textures_keep_original(
#		VisualServer.viewport_attach_camera(
#		VisualServer.viewport_attach_canvas(
#		VisualServer.viewport_attach_to_screen(
#		VisualServer.viewport_create()
#		VisualServer.viewport_detach(
#		VisualServer.viewport_get_render_info(
#		VisualServer.viewport_get_texture(
#		VisualServer.viewport_remove_canvas(
#		VisualServer.viewport_set_active(
#		VisualServer.viewport_set_canvas_stacking(
#		VisualServer.viewport_set_canvas_transform(
#		VisualServer.viewport_set_clear_mode(
#		VisualServer.viewport_set_debug_draw(
#		VisualServer.viewport_set_disable_3d(
#		VisualServer.viewport_set_disable_environment(
#		VisualServer.viewport_set_global_canvas_transform(
#		VisualServer.viewport_set_hdr(
#		VisualServer.viewport_set_hide_canvas(
#		VisualServer.viewport_set_hide_scenario(
#		VisualServer.viewport_set_msaa(
#		VisualServer.viewport_set_parent_viewport(
#		VisualServer.viewport_set_render_direct_to_screen(
#		VisualServer.viewport_set_scenario(
#		VisualServer.viewport_set_shadow_atlas_quadrant_subdivision(
#		VisualServer.viewport_set_shadow_atlas_size(
#		VisualServer.viewport_set_size(
#		VisualServer.viewport_set_transparent_background(
#		VisualServer.viewport_set_update_mode(
#		VisualServer.viewport_set_usage(
#		VisualServer.viewport_set_use_arvr(
#		VisualServer.viewport_set_vflip(
#
